testa/urls.py
from django.conf.urls import patterns, include, url
from reg.views import index,checklogin,student_reg,client_reg,activate_user,forgot_password,forgot_password_email,forgot_password_handler,new_password,change_password,change_password_handler,log_out
from quiz.views import test_sync,upload,take_test,test_apply,evaluate_test
from users.views import client_dashboard_student,student_bio,client_bio,student_test_landing,test_analysis,student_dashboard_ongoingtests,client_dashboard,client_dashboard_tests,student_dashboard_takentests,student_dashboard_appliedtests,student_dashboard_personal,student_dashboard_approvedtests,student_dashboard,student_applytest,student_dashboard_closedtests,student_dashboard_tests,student_test,student_dashboard_opentests,approve_test,jqgrid_handler,jqgrid_handler2
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'testa.views.home', name='home'),
    # url(r'^testa/', include('testa.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
   url(r'^admin/', include(admin.site.urls)),	
   url(r'^$',index),
	url(r'^logout/$',log_out),
	url(r'^checklogin/$',checklogin),
	url(r'^client-dashboard/$',client_dashboard),
	url(r'^client-dashboard/client-tests/$',client_dashboard_tests),
	url(r'^client-dashboard/bio/$',client_bio),
	url(r'^client-dashboard/student/(?P<student_id>\d+)$',client_dashboard_student),
	url(r'^student-dashboard/bio/$',student_bio),
	url(r'^student-dashboard/personal/$',student_dashboard_personal),
	url(r'^student-dashboard/personal/applied/$',student_dashboard_appliedtests),
	url(r'^student-dashboard/tests/ongoing/$',student_dashboard_ongoingtests),
	url(r'^student-dashboard/tests/approved/$',student_dashboard_approvedtests),
	url(r'^student-dashboard/tests/taken/$',student_dashboard_takentests),
	url(r'^landing/(\w+)/(?P<test_key>[\w,-]+)$',student_test_landing),
	url(r'^student-dashboard/tests/analysis/(?P<test_id>\d+)$',test_analysis),
	url(r'^student-dashboard/$',student_dashboard),
	url(r'^student-dashboard/tests/$',student_dashboard_tests),
	url(r'^student-dashboard/tests/open-tests/$',student_dashboard_opentests),
	url(r'^student-dashboard/tests/closed-tests/$',student_dashboard_closedtests),
	url(r'^student-dashboard/tests/apply/(?P<test_id>\d+)/$',student_applytest),
	url(r'^student-reg/$',student_reg),
	url(r'^test-sync/$',test_sync),
	url(r'^apply/(?P<test_id>\d+)$',test_apply),
	url(r'^approve/$',approve_test),
	url(r'^start/(\w+)/(?P<test_key>[\w,-]+)/$',take_test),
	url(r'^start/(\w+)/(?P<test_key>[\w,-]+)/evaluate/$',evaluate_test),
	url(r'^client-reg/$',client_reg),
	url(r'^activate/(?P<a_string>\w{30})/$',activate_user),
	url(r'^forgot-password/$',forgot_password),
	url(r'^fp-email/$',forgot_password_email),
	url(r'^fp-string/(?P<fp_string>\w{30})/$',forgot_password_handler),
	url(r'^new-password/$',new_password),
	url(r'^change-password/$',change_password),
	url(r'^cp-handler/$',change_password_handler),
	url(r'^client-dashboard/upload-test/$',upload),
	url(r'^jqgrid-handler/$',jqgrid_handler),
	url(r'^jqgrid-handler2/$',jqgrid_handler2),
	url(r'^test/(\w+)/(?P<test_key>[\w,-]+)$',student_test),
	
)

urlpatterns += staticfiles_urlpatterns()

quiz/models.py
from django.db import models
from users.models import client
from django.contrib.auth.models import User
import os
import testa.settings
from users.models import student,client


def get_path(instance,filename):
	user = instance.user_id
	return os.path.join('tests','/',filename)
	
QUIZ_CHOICES = (
('1','open'),
('2','closed'),
('3','secure')
)


class quiz(models.Model):
	client = models.ForeignKey(client)
	title = models.CharField(max_length=200)
	description = models.TextField()
	questions_file = models.FileField(upload_to='tests')
	start_time = models.DateTimeField()
	end_time = models.DateTimeField()
	duration = models.IntegerField()
	applicationJSON = models.TextField()
	number_of_questions = models.IntegerField()
	type = models.CharField(choices = QUIZ_CHOICES, max_length = 10, default = '1')
	key = models.CharField(max_length = 100)
	def __unicode__(self):
		return self.title



class testQuestion(models.Model):
	quiz = models.ForeignKey(quiz)
	question = models.CharField(max_length=1000)
	option_a = models.CharField(max_length=500)
	option_b = models.CharField(max_length=500)
	option_c = models.CharField(max_length=500)
	option_d = models.CharField(max_length=500)
	correct_answer = models.CharField(max_length=50)
	
	
	
class StudentTest(models.Model):
	student = models.ForeignKey(student)
	quiz = models.ForeignKey(quiz)
	applicationJSON = models.TextField()
	apply_datetime = models.DateTimeField(null=True,blank=True)
	test_datetime = models.DateTimeField(null=True,blank=True)
	approved = models.BooleanField(default=False)
	score = models.CharField(max_length = 100)
	finish_datetime = models.DateTimeField(null=True,blank=True)
	taken = models.NullBooleanField(default = None)	
	
class StudentTestQA(models.Model):
	student_test = models.ForeignKey(StudentTest)
	question = models.TextField()
	answer = models.TextField()

	
class TestBackup(models.Model):
	student = models.ForeignKey(student)
	quiz = models.ForeignKey(quiz)
	question=models.TextField()
	answer = models.TextField()
	current_datetime = models.DateTimeField()

reg/forms.py
from django import forms

class loginForm(forms.Form):
	username = forms.CharField(max_length=100)
	password = forms.CharField(widget=forms.PasswordInput())
	
class clientRegistrationForm(forms.Form):
	username = forms.CharField(max_length=100)
	password = forms.CharField(widget=forms.PasswordInput())
	email = forms.EmailField()
	first_name = forms.CharField(max_length=100)
	last_name = forms.CharField(max_length=100)
	details = forms.CharField(widget=forms.Textarea,max_length=500)



class studentRegistrationForm(forms.Form):
	username = forms.CharField(max_length=100)
	password = forms.CharField(widget=forms.PasswordInput())
	email = forms.EmailField()
	first_name = forms.CharField(max_length=100)
	last_name = forms.CharField(max_length=100)
	college = forms.CharField(max_length = 250)
	department_choices = (
                ('IT', 'IT'),
                ('CSE', 'CSE'),
                ('MCA', 'MCA'),
                ('BT', 'BT'),
                ('CE', 'CE'),
                ('CHE', 'CHE'),
                ('ECE', 'ECE'),
                ('EE', 'EE'),
                ('ME', 'ME'),
                ('MME', 'MME'),
                ('Other', 'Other'),
            )
	department = forms.ChoiceField(choices=department_choices)
	year_choices = (
					 ('2014', '2014'),
                ('2015', '2015'),                
                ('2016', '2016'),
        )
	year = forms.ChoiceField(choices=year_choices,label = 'Expected year of passing')
	phone = forms.IntegerField()
	

templates/base.html
<html>
<head>
    <title>Testa</title>


{%block head%}

<link rel="stylesheet" type="text/css" media="screen" href="/static/css/bootstrap.css" />
<link rel="stylesheet" type="text/css" media="screen" href="/static/css/jquery-ui-1.10.3.custom.min.css" />
<link rel="stylesheet" type="text/css" media="screen" href="/static/css/ui.jqgrid.css" />
<script src="/static/js/jquery.min.js" type="text/javascript"></script>
<script src="/static/js/bootstrap.min.js" type="text/javascript"></script>
<script src="/static/js/grid.locale-en.js" type="text/javascript"></script>
<script src="/static/js/jquery.jqGrid.min.js" type="text/javascript"></script>


{% endblock %}

</head>
<body>

<div class="navbar navbar-fixed-top">  
<div class="navbar-inner">  
<div class="container">  
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">  
<span class="icon-bar"></span>  
<span class="icon-bar"></span>  
<span class="icon-bar"></span>  
</a>  

<div class="nav-collapse">  
<a href='#' class = 'brand'>Testa</a>
<ul class="nav pull-right">  
 {% if user.is_authenticated %}

 <li class="dropdown">
            <a class="dropdown-toggle" href="#" data-toggle="dropdown">Profile <strong class="caret"></strong></a>

            <ul class="dropdown-menu" >
            {% if request.session.group == 'client' %}
            <li> <a href="/client-dashboard/bio">Bio</a> </li>
            <li><a href="/client-dashboard/" >Dashboard</a></li>
            {% else %}
            <li> <a href="/student-dashboard/bio">Bio</a> </li>
            <li><a href="/student-dashboard/" >Dashboard</a></li>
            {% endif %}
            </ul> 

          </li>
 <li><a href='/logout/'>Logout</a></li>








	{% else %}
	
 <li class="dropdown">
            <a class="dropdown-toggle" href="#" data-toggle="dropdown">Sign In <strong class="caret"></strong></a>
            <div class="dropdown-menu" style="padding: 15px; padding-bottom: 0px;">
              <form action='/checklogin/' method='POST'>
		{% csrf_token %}
		 {{loginform.as_table}}
<input class = 'btn btn-danger' type='submit' name='submit'>
</form>
            </div>
          </li>
 <li class="dropdown">
            <a class="dropdown-toggle" href="#" data-toggle="dropdown">Register <strong class="caret"></strong></a>
            <ul class="dropdown-menu" >
		
		<li><a href='/student-reg/'>Student</a></li>
		<li><a href='/client-reg/'>Client</a></li>
		
            </ul> </li>


{% endif %}
</ul>  
</div>
</div>  
</div>  
</div>



<div class= ' span11 offset1 ' style = 'margin-top:50px'>

{%block content%}



{% endblock %}

</div>
</body>

</html>

templates/change_password.html
{% extends 'student-dashboard.html' %}


{% block title %}
<title>Applied Tests</title>
{% endblock %}

{% block navlist %}
<ul class="nav nav-list">
	 <li class='nav-header'>
	 Tests
	 </li>
    <li>
        <a href="/student-dashboard/personal/applied/" style="background-image: none; background-position: 0% 0%; background-repeat: repeat repeat;">Applied</a>
    </li>
     <li>
    		<a href="/student-dashboard/tests/approved/" style="background-image: none; background-position: 0% 0%; background-repeat: repeat repeat;">Approved</a>
    </li>
    <li>
        <a href="/student-dashboard/tests/taken/" style="background-image: none; background-position: 0% 0%; background-repeat: repeat repeat;">Taken</a>
    </li>
            <li>
        <a href="/student-dashboard/tests/ongoing/" style="background-image: none; background-position: 0% 0%; background-repeat: repeat repeat;">Ongoing</a>
    </li>
    <li class='nav-header'>
	 Profile
	 </li>
	  <li>
        <a href="/student-dashboard/student/bio/" >Edit Profile</a>
    </li>
	 <li class ="active">
        <a href="/change-password/" >Change password</a>
    </li>
</ul>
{% endblock %}

{% block breadcrumb %}
 <ul class="breadcrumb">
  <li>
      <a href="/student-dashboard/personal" style="background-image: none; background-position: 0% 0%; background-repeat: repeat repeat;">Personal</a> <span class="divider">/</span>

  </li>
  <li class="active">Change Password</li>
 </ul>
 {% endblock %}

 {% block content %}
<body>

{% if message %}
<div class="alert">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  {{message}}
</div>
{% endif %}

<form action='/cp-handler/' method='POST'>
{% csrf_token %}
<p>Old Password</p> <input name='old_password' type="Password"> </input>
<p>New Password</p> <input name='new_password' type="Password"> </input><br/>
<input type='submit' name='submit'>
</form>



 {% endblock %}

templates/client-dashboard.html
<!doctype html>
<html>
    
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8" >
        {% block title %}
        <title>Client Dashboard</title>
        {% endblock %}

<link rel="stylesheet" type="text/css" media="screen" href="/static/css/bootstrap.css" />
<link rel="stylesheet" type="text/css" media="screen" href="/static/css/jquery-ui-1.10.3.custom.min.css" />
<link rel="stylesheet" type="text/css" media="screen" href="/static/css/ui.jqgrid.css" />
<link rel="stylesheet" type="text/css" media="screen" href="/static/css/bootstrap-datetimepicker.min.css" />
<script src="/static/js/jquery.min.js" type="text/javascript"></script>
<script src="/static/js/bootstrap.min.js" type="text/javascript"></script>
<script src="/static/js/grid.locale-en.js" type="text/javascript"></script>
<script src="/static/js/jquery.jqGrid.min.js" type="text/javascript"></script>
<script src="/static/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>

{% block extraincludes %}
{% endblock %}
    </head>
    
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <a class="brand" href="/client-dashboard/">Client dashboard</a>
                <ul class="nav pull-right">  
 <li><a href='/logout/'>Logout</a></li>
 </ul>
            </div>
        </div>
        <div class="container-fluid" style="margin-top:70px">
            <div class="container-fluid">
                <div class="container-fluid">
                    <div class="span3">
                    {% block navlist %}
                        <ul class="nav nav-list">
<li class='nav-header'>
	 Tests
	 </li>
                            <li >
                                <a href="/client-dashboard/client-tests" style="background-image: none; background-position: 0% 0%; background-repeat: repeat repeat;">Your tests</a>
                            </li>
                            <li>
                                <a href="/client-dashboard/upload-test" style="background-image: none; background-position: 0% 0%; background-repeat: repeat repeat;">Upload a test</a>
                            </li>
                           <li class='nav-header'>
	 Personal
	 </li>
								 <li >
							        <a href="/change-password/" >Change password</a>
							    </li>
							    <li >
							        <a href="/client-dashboard/bio" >View Profile</a>
							    </li>

                        </ul>
                     {% endblock %}
                    </div>
                    <div class="span7">
                        <div class="container-fluid">
                        	{% block breadcrumb %}
                            <ul class="breadcrumb">
                             </ul>
                            {% endblock %}
                            
                            {% block content %}
                             <h3 style="background-image: none; background-position: 0% 0%; background-repeat: repeat repeat;">Client Dashboard</h3>

                            <p class="">Lorem ipsum dolor sit amet, consectetur adipiscing elit. In at felis urna,
                                eget aliquam mauris. Etiam sed augue arcu. Quisque ullamcorper pharetra
                                leo, id tempus elit viverra eu. Duis viverra lorem at dui imperdiet rutrum.
                                Sed lobortis enim tortor, id sed.</p>
   
                            
                            {% endblock %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

templates/client-registration.html
{% extends 'base.html' %}



{% block content %}


<body>

   <div class="row container">
<h2 class="offset1">Client Registration</h2>
        <div class="span4 pull-left well" style="margin-left:-40px" >
            <h3>CLIENT REGISTRATION:</h3>
            The reason Lorem Ipsum is the old standby is that it contains full paragraphs of greeked words that mirror actual patterns of text. Using the same sentence repeatedly will give you a false impression of how text will really look on the page and will create "rivers" of white through the paragraphs due to the repetition of the same number of characters and spaces. I can't imagine this would be useful for anything beyond a sentence or two.
        </div> 
        <div class="span7 pull-right " id="form">
            <div class="span7 pull-right"  >
{% if errors %}
<div class="alert">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  {{errors}}
</div>
{% endif %}
<form action='/client-reg/' method='POST'>
{% csrf_token %}

 
                    <p class="span3 pull-left"><label for="id_username">Username:</label> <input id="id_username" type="text" name="username" maxlength="100" placeholder="Username" required autofocus /></p>
                    <p class="span3 pull-right"><label for="id_email">Email:</label> <input type="email" name="email" id="id_email" placeholder="example@example.com" required /></p>
            </div>


            <div class="span7 pull-right" >
                <p class="span3 pull-left"><label for="id_password">Password:</label> <input type="password" name="password"  pattern=".{6,}" placeholder="Password" id="id_password"  required/></p>
                <p class="span3 pull-right"><label for="id_retype_password">Retype Password:</label> <input type="password" placeholder="Re-type Password"  pattern=".{6,}"  name="retype_password" id="id_retype_password" required /></p>
            </div>

            <div class="span7 pull-right" >
                <div class="span3 pull-left" >
                    <p><label for="id_first_name">First name:</label> <input id="id_first_name" type="text" name="first_name" maxlength="100" placeholder="First Name" required /></p>
                </div>

                <div class="span3 pull-right" >
                    <p><label for="id_last_name">Last name:</label> <input id="id_last_name" type="text" name="last_name" maxlength="100" placeholder="Last Name" required  /></p>
                </div>

                <div class="span7 pull-right" >
                    <div class="span6" >
                        <p><label for="id_details">Details:</label> <textarea id="id_details" class="span7" rows="5" cols="100" name="details"></textarea></p>
                    </div>
                </div>
                <input class="btn btn-inverse span7" type='submit' name='submit' value="REGISTER" style="margin-left: 20px; height: 60px !important;font-size:20px">
</form>
</div>
</div>
       </div>
</body>


{% endblock %}

templates/client-student.html
{% extends 'client-dashboard.html' %}










 {% block navlist %}
                        <ul class="nav nav-list">
                        <li class='nav-header'>
	 Tests
	 </li>
                            <li class="active">
                                <a href="/client-dashboard/client-tests" style="background-image: none; background-position: 0% 0%; background-repeat: repeat repeat;">Your tests</a>
                            </li>
                            <li>
                                <a href="/client-dashboard/upload-test" style="background-image: none; background-position: 0% 0%; background-repeat: repeat repeat;">Upload a test</a>
                            </li>
                            <li class='nav-header'>
	 Personal
	 </li>
                             <li >
							        <a href="/change-password/" >Change password</a>
							    </li>
								<li>
							        <a href="/client-dashboard/bio" >View Profile</a>
							    </li>
                        </ul>
                     {% endblock %}





{% block content %}
  <h4 style="background-image: none; background-position: 0% 0%; background-repeat: repeat repeat;">Student Profile</h4>

<p class="lead">{{details.name}}</p>
<p >{{details.username}}</p>
 <p >{{details.email}}</p>
<p >{{details.college}}</p>
<p >{{details.department}}</p>
<p >{{details.year}}</p>
 {% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
<body>


{% if message %}
<div class="alert">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
{{message}}
</div>
{% endif %}
<h1>content</h1>

</body>
{% endblock %}

templates/login.html
{% extends 'base.html' %}



{% block content %}
<body>
<form action='/checklogin/' method='POST'>
{% csrf_token %}
{{form.as_p}}
<input type='submit' name='submit'>
</form>
</body>
{% endblock %}

templates/new_password.html
{% extends 'base.html' %}



{% block content %}

<body>
<form action='/new-password/' method='POST'>
{% csrf_token %}
<input name='password' type="password">New password</input>
<input type='submit' name='submit'>
</form>
</body>




{% endblock %}

templates/student-approvedtests.html
{% extends 'student-dashboard.html' %}


{% block title %}
<title>Approved Tests</title>
{% endblock %}

{% block navlist %}
<ul class="nav nav-list">
	 <li class='nav-header'>
	 Tests
	 </li>
    <li >
        <a href="/student-dashboard/personal/applied/" style="background-image: none; background-position: 0% 0%; background-repeat: repeat repeat;">Applied</a>
    </li>
     <li class="active">
    		<a href="/student-dashboard/tests/approved/" style="background-image: none; background-position: 0% 0%; background-repeat: repeat repeat;">Approved</a>
    </li>
    <li>
        <a href="/student-dashboard/tests/taken/" style="background-image: none; background-position: 0% 0%; background-repeat: repeat repeat;">Taken</a>
    </li>
        <li>
        <a href="/student-dashboard/tests/ongoing/" style="background-image: none; background-position: 0% 0%; background-repeat: repeat repeat;">Ongoing</a>
    </li>
    <li class='nav-header'>
	 Profile
	 </li>
	  <li>
        <a href="/student-dashboard/bio/" >View Profile</a>
    </li>
	 <li>
        <a href="/change-password/" >Change password</a>
    </li>
</ul>
{% endblock %}

{% block breadcrumb %}
 <ul class="breadcrumb">
  <li>
      <a href="/student-dashboard/personal" style="background-image: none; background-position: 0% 0%; background-repeat: repeat repeat;">Personal</a> <span class="divider">/</span>

  </li>
  <li class="active">Approved tests</li>
 </ul>
 {% endblock %}

 {% block content %}
  <h3 style="background-image: none; background-position: 0% 0%; background-repeat: repeat repeat;">Approved Tests</h3>
 


            <table class="table table-hover ">
                <tbody>
                    <tr>
                        <th>Test</th>
                        <th>End-date</th>
                        <th>Uploader</th>
                        <th>Time</th>
                        <th>No. of questions</th>
                    </tr>
                   
                     	{% for test in approvedList %}
 <tr>
								<td><a href="/test/{{test.client}}/{{test.test_key}}">{{test.title}}</a></td>
								<td>{{test.end_date}}</td>
								<td>{{test.client}}</td>
							  <td>{{test.duration}}</td>
							<td>{{test.length}}</td>
     </tr>
								{% endfor %}  
               

                </tbody>
            </table>

 {% endblock %}

templates/upload.html
{% extends 'client-dashboard.html' %}


 {% block navlist %}
                        <ul class="nav nav-list">
<li class='nav-header'>
	 Tests
	 </li>
                            <li>
                                <a href="/client-dashboard/client-tests" style="background-image: none; background-position: 0% 0%; background-repeat: repeat repeat;">Your tests</a>
                            </li>
                            <li class="active">
                                <a href="/client-dashboard/upload-test" style="background-image: none; background-position: 0% 0%; background-repeat: repeat repeat;">Upload a test</a>
                            </li>
                            <li class='nav-header'>
	 Personal
	 </li>
                             <li>
							        <a href="/change-password/" >Change password</a>
							    </li>
							    								<li>
							        <a href="/client-dashboard/bio" >View Profile</a>
							    </li>
                        </ul>
                     {% endblock %}




{% block content %}

<body>
    <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/1.8.3/jquery.min.js"> </script> 
    <script type="text/javascript" src="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.2.2/js/bootstrap.min.js"> </script>
    <script type="text/javascript" src="http://tarruda.github.com/bootstrap-datetimepicker/assets/js/bootstrap-datetimepicker.min.js"> </script>
    
    
     <script type="text/javascript">
      
        $(document).ready(function() {
 	 $('#btnAdd').hide();
 	 $('#btnDel').hide(); 
        
$('#id_type').change(function() {
  if($('#id_type').val()!=2){
  	
 	 $('#btnAdd').hide();
 	 $('#btnDel').hide();  
  }
  else{
  console.log('2')
   	$('#btnAdd').fadeIn();
 	 $('#btnDel').fadeIn(); 
  
  }
});     $('#uploadform input').attr('required','true')
		  $('#id_number_of_questions').attr('placeholder','less than questions in xls')
		  $('#id_title').attr('placeholder','Name of your test.')
		  $('#id_start_time').attr('placeholder','Test enable time')
		  $('#id_end_time').attr('placeholder','Test expiration time')
		  $('#id_description').attr('placeholder','About your test.')
		  $('#id_duration').attr('placeholder','In minutes') 
        $('#id_questions_file').after("<a id='type-help' href='#' rel='tooltip' data-placement='right' title='Your xls file should have the following format: 1st row - Question. 2nd-5th row - options. 6th row - correct answer i.e. a,b,c or d'><i class='icon-question-sign'></i></a>")
        $('#id_type').after("<a id='xls-help' href='#' rel='tooltip' data-placement='right' title='Open: All students can take your test. Closed: Students apply for the test. You can add questions to the application. Secret: Students cannot see your test. You have to mail them the test link. '><i class='icon-question-sign'></i></a>")
        $("#type-help").tooltip();
        $("#xls-help").tooltip();
        
            $('#btnAdd').click(function() {
            var num = $('.applyq').length + 1;
				$('#questions').append(
  $('<input>')
    .attr("id", "q"+ num)
    .attr("name","q" + num)
	.attr("type","text")
    .addClass('applyq')
);
 $('#no_q').val(num)       ;       
 				});
 				
            $('#btnDel').click(function() {
            var num = $('.applyq').length;
            $('#q'+ num).remove()
            
            });

$('#id_start_time').wrap('<div id="dt1" class="input-append date"/>');
$('#id_end_time').wrap('<div id="dt2" class="input-append date"/>');
$('#id_start_time').after("<span class='add-on'><i data-time-icon='icon-time' data-date-icon='icon-calendar'></i></span>");
$('#id_end_time').after("<span class='add-on'><i data-time-icon='icon-time' data-date-icon='icon-calendar'></i></span>");


      $('#dt2').datetimepicker({
        format: 'yyyy-MM-dd hh:mm',
        language: 'en',
        pickSeconds: false
      });
      
            $('#dt1').datetimepicker({
        format: 'yyyy-MM-dd hh:mm',
        language: 'en',
        pickSeconds: false
      });



        });
    </script>
 
{% if message %}
<div class="alert">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  {{message}}
</div>
{% endif %}
<form id='uploadform' enctype="multipart/form-data" action='/client-dashboard/upload-test/' method='POST'>
{% csrf_token %}
{{form.as_p}}

<input id="no_q" name="no_q" type="hidden" value="0"></input>

    <div>
        <input type="button" id="btnAdd" value="Add questions" />
        <input type="button" id="btnDel" value="Remove questions" />
    </div>
    <div id="questions" class="span4" style="padding:20px"></div>
        
    
    </div>
     
<input id='submit' type='submit' name='submit'>
</form>
 
 
</body>
{% endblock %}